-- *********************************************************************************
-- * Generated by SqlDBM: Oracle SampleDb, v54 by alexey.alferov+oracle@sqldbm.com *


CREATE SCHEMA AUTHORIZATION "DataTypes"
-- ************************************** "DataTypes"."datatypes"
CREATE TABLE "DataTypes"."datatypes"
(
 "Oracle_built_in_datatypes" NUMBER(1,0) NOT NULL,
 "ANSI_supported_datatypes"  NUMBER(1,0) NOT NULL,
 "user_defined_types"        NUMBER(1,0) NOT NULL,
 "Oracle_supplied_types"     NUMBER(1,0) NOT NULL
)
-- ************************************** "DataTypes"."Oracle_built_in_datatypes"
CREATE TABLE "DataTypes"."Oracle_built_in_datatypes"
(
 "character_datatypes"    VARCHAR2 NOT NULL,
 "number_datatypes"       VARCHAR2 NOT NULL,
 "long_and_raw_datatypes" VARCHAR2 NOT NULL,
 "datetime_datatypes"     VARCHAR2 NOT NULL,
 "large_object_datatypes" VARCHAR2 NOT NULL,
 "rowid_datatypes"        VARCHAR2 NOT NULL
)
-- ************************************** "DataTypes"."character_datatypes"
CREATE TABLE "DataTypes"."character_datatypes"
(
 "col_char"        CHAR NOT NULL,
 "col_char_1"      CHAR(5) NOT NULL,
 "col_char_2"      CHAR(6 BYTE) NOT NULL,
 "col_char_3"      CHAR(6 CHAR) NOT NULL,
 "col_varchar2"    VARCHAR2 NOT NULL,
 "col_varchar2_1"  VARCHAR2(10) NOT NULL,
 "col_varchar2_2"  VARCHAR2(10 BYTE) NOT NULL,
 "col_varchar2_3"  VARCHAR2(10 CHAR) NOT NULL,
 "col_nchar"       NCHAR NOT NULL,
 "col_nchar_1"     NCHAR(7) NOT NULL,
 "col_nvarchar2"   NVARCHAR2 NOT NULL,
 "col_nvarchar2_1" NVARCHAR2(4) NOT NULL
)
-- ************************************** "DataTypes"."large_object_datatypes"
CREATE TABLE "DataTypes"."large_object_datatypes"
(
 "col_1" BLOB NOT NULL,
 "col_2" CLOB NOT NULL,
 "col_3" NCLOB NOT NULL,
 "col_4" BFILE NOT NULL
)
-- ************************************** "DataTypes"."long_and_raw_datatypes"
CREATE TABLE "DataTypes"."long_and_raw_datatypes"
(
 "col_long"    LONG NOT NULL,
 "col_longraw" LONG RAW NOT NULL,
 "col_raw"     RAW NOT NULL,
 "col_raw_1"   RAW(5) NOT NULL
)
-- ************************************** "DataTypes"."rowid_datatypes"
CREATE TABLE "DataTypes"."rowid_datatypes"
(
 "col_rowid"    ROWID NOT NULL,
 "col_urowid"   UROWID NOT NULL,
 "col_urowid_1" UROWID(6) NOT NULL
)
-- ************************************** "DataTypes"."datetime_datatypes"
CREATE TABLE "DataTypes"."datetime_datatypes"
(
 "col_date"                                   DATE NOT NULL,
 "col_timestamp"                              TIMESTAMP NOT NULL,
 "col_timestamp_fractional_seconds_precision" TIMESTAMP(0) NOT NULL,
 "col_timestamp_with_local_timezone"          TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
 "col_timestamp_with_timezone"                TIMESTAMP WITH TIME ZONE NOT NULL,
 "col_timestamp_fsp_with_local_timezone"      TIMESTAMP(0) WITH LOCAL TIME ZONE NOT NULL,
 "col_timestamp_fsp_with_timezone"            TIMESTAMP(0) WITH TIME ZONE NOT NULL,
 "col_interval_year_to_month"                 INTERVAL YEAR TO MONTH NOT NULL,
 "col_interval_year_yp_to_month"              INTERVAL YEAR (0) TO MONTH NOT NULL,
 "col_interval_day_to_second"                 INTERVAL DAY TO SECOND NOT NULL,
 "col_interval_day_to_second_fsp"             INTERVAL DAY TO SECOND(2) NOT NULL,
 "col_interval_day_dp_to_second"              INTERVAL DAY (0) TO SECOND NOT NULL,
 "col_interval_day_dp_to_second_fsp"          INTERVAL DAY(1) TO SECOND(2) NOT NULL
)
-- ************************************** "DataTypes"."number_datatypes"
CREATE TABLE "DataTypes"."number_datatypes"
(
 "col_number"        NUMBER NOT NULL,
 "col_number_1"      NUMBER(3) NOT NULL,
 "col_number_2"      NUMBER(4, 3) NOT NULL,
 "col_float"         FLOAT NOT NULL,
 "col_float_1"       FLOAT(10) NOT NULL,
 "col_binary_float"  BINARY_FLOAT NOT NULL,
 "col_binary_double" BINARY_DOUBLE NOT NULL
);

CREATE SCHEMA AUTHORIZATION "InvisibleColumns"
-- ************************************** "InvisibleColumns"."j_invisible"
CREATE TABLE "InvisibleColumns"."j_invisible"
(
 "i" INT NOT NULL,
 "j" DATE INVISIBLE NOT NULL
)
-- ************************************** "InvisibleColumns"."j_visible"
CREATE TABLE "InvisibleColumns"."j_visible"
(
 "i" INT NOT NULL,
 "j" DATE VISIBLE NOT NULL
);

CREATE SCHEMA AUTHORIZATION "InvisibleDefaultValues"
-- ************************************** "InvisibleDefaultValues"."k_invisible_default"
CREATE TABLE "InvisibleDefaultValues"."k_invisible_default"
(
 "a" INT NOT NULL,
 "k" DATE INVISIBLE NOT NULL DEFAULT 6
)
-- ************************************** "InvisibleDefaultValues"."k_visible"
CREATE TABLE "InvisibleDefaultValues"."k_visible"
(
 "a" INT NOT NULL,
 "k" DATE VISIBLE NOT NULL DEFAULT 0
)
-- ************************************** "InvisibleDefaultValues"."k_invisible_default_copy_1"
CREATE TABLE "InvisibleDefaultValues"."k_invisible_default_copy_1"
(
 "a" INT NOT NULL,
 "k" DATE INVISIBLE NOT NULL DEFAULT 1998-DEC-25 17:30
);

CREATE SCHEMA AUTHORIZATION "samvel"
-- ************************************** "samvel"."suppliers"
CREATE TABLE "samvel"."suppliers"
(
 "supplier_id"   NUMBER (10) NOT NULL,
 "supplier_name" VARCHAR2 (50) NOT NULL,
 "city"          VARCHAR2 (25) NOT NULL,
 CONSTRAINT "suppliers_pk" PRIMARY KEY ("supplier_id")
)
-- ************************************** "samvel"."table_17"
CREATE TABLE "samvel"."table_17"
(

)
-- ************************************** "samvel"."products"
CREATE TABLE "samvel"."products"
(
 "product_id"   NUMBER (10) NOT NULL,
 "product_name" VARCHAR2 (50) NOT NULL,
 "supplier_id"  NUMBER (10) NOT NULL,
 "category"     VARCHAR2 (50) NOT NULL,
 CONSTRAINT "products_pk" PRIMARY KEY ("product_id"),
 CONSTRAINT "FK_1" FOREIGN KEY ("supplier_id") REFERENCES "samvel"."suppliers" ("supplier_id")
);

