-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


CREATE SCHEMA AUTHORIZATION "InvisibleDefaultValues"
-- ************************************** "InvisibleDefaultValues"."k_invisible_default"
CREATE TABLE "InvisibleDefaultValues"."k_invisible_default"
(
 "a" INT NOT NULL,
 "k" DATE INVISIBLE NOT NULL DEFAULT 6
)
-- ************************************** "InvisibleDefaultValues"."k_visible"
CREATE TABLE "InvisibleDefaultValues"."k_visible"
(
 "a" INT NOT NULL,
 "k" DATE VISIBLE NOT NULL DEFAULT 0
)
-- ************************************** "InvisibleDefaultValues"."k_invisible_default_copy_1"
CREATE TABLE "InvisibleDefaultValues"."k_invisible_default_copy_1"
(
 "a" INT NOT NULL,
 "k" DATE INVISIBLE NOT NULL DEFAULT 1998-DEC-25 17:30
);
