-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


CREATE SCHEMA AUTHORIZATION "InvisibleColumns"
-- ************************************** "InvisibleColumns"."j_invisible"
CREATE TABLE "InvisibleColumns"."j_invisible"
(
 "i" INT NOT NULL,
 "j" DATE INVISIBLE NOT NULL
)
-- ************************************** "InvisibleColumns"."j_visible"
CREATE TABLE "InvisibleColumns"."j_visible"
(
 "i" INT NOT NULL,
 "j" DATE VISIBLE NOT NULL
);
