-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


CREATE SCHEMA AUTHORIZATION "samvel"
-- ************************************** "samvel"."suppliers"
CREATE TABLE "samvel"."suppliers"
(
 "supplier_id"   NUMBER (10) NOT NULL,
 "supplier_name" VARCHAR2 (50) NOT NULL,
 "city"          VARCHAR2 (25) NOT NULL,
 CONSTRAINT "suppliers_pk" PRIMARY KEY ("supplier_id")
)
-- ************************************** "samvel"."table_17"
CREATE TABLE "samvel"."table_17"
(

)
-- ************************************** "samvel"."products"
CREATE TABLE "samvel"."products"
(
 "product_id"   NUMBER (10) NOT NULL,
 "product_name" VARCHAR2 (50) NOT NULL,
 "supplier_id"  NUMBER (10) NOT NULL,
 "category"     VARCHAR2 (50) NOT NULL,
 CONSTRAINT "products_pk" PRIMARY KEY ("product_id"),
 CONSTRAINT "FK_1" FOREIGN KEY ("supplier_id") REFERENCES "samvel"."suppliers" ("supplier_id")
);
